## #####################################################
## Firebase
##
.deploy_firebase_template: &deploy_firebase_def
  image: evenbit/firebase
  stage: deploy
  cache:
    paths:
      - .firebase
      - dist/node_modules/
      - functions/node_modules/
      - angular/node_modules/
  before_script:
    - node --version
    - firebase --version
    - npm --prefix functions install
    - npm --prefix angular install
  after_script:
    - npm --prefix functions run build:dist
    - npm --prefix dist install
    - firebase deploy -m "Gitlab pipeline $CI_PIPELINE_ID, build $CI_JOB_ID" --non-interactive --force --token $FIREBASE_DEPLOY_KEY

deploy_firebase_production:
  <<: *deploy_firebase_def
  environment: Production
  only:
    - master
  script:
    - firebase use $FIREBASE_PRODUCTION_PROJECT_ID
    - firebase use production --token $FIREBASE_DEPLOY_KEY

deploy_firebase_development:
  <<: *deploy_firebase_def
  environment: Development
  only:
    - develop
  script:
    - firebase use $FIREBASE_DEVELOP_PROJECT_ID
    - firebase use develop --token $FIREBASE_DEPLOY_KEY
