language: node_js
node_js:
  - "8"
cache:
  - angular/node_modules
  - dist/node_modules
  - functions/node_modules
branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+/
before_script:
  - cd angular
  - npm install
  - cd ../functions
  - npm install
  - npm run build:dist
  - cd ../dist
  - npm install
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script:
        - cd dist
        - npm publish
      on:
        tags: true
