language: node_js
node_js:
  - "8"
cache:
  - node_modules
branches:
  only:
    - master
before_script:
    - npm --prefix src/admin_client install
    - npm --prefix src/admin_client run build
script: echo "npm test is temporarily disabled"
deploy:
  provider: npm
  email: contact@oddbit.id
  api_key: $NPM_TOKEN
