language: node_js
node_js:
  - "8"
cache:
  - functions/node_modules
  - dist/node_modules
branches:
  only:
  - master
before_script:
  - npm --prefix functions run build:dist
script:
  - echo "npm test is temporarily disabled"
deploy:
  provider: npm
  email: dennis@oddbit.id
  api_key: $NPM_TOKEN
  on:
    tags: true
