language: node_js
node_js:
  - "8"
cache:
  - angular/node_modules
  - dist/node_modules
  - functions/node_modules
branches:
  only:
  - develop
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+/
script:
  - cd angular
  - npm install
  - cd ../functions
  - npm install
  - npm run build:dist
before_deploy:
  - cd ../dist
  - ls
  - npm install
deploy:
  skip_cleanup: true
  provider: npm
  email: dennis@oddbit.id
  api_key: $NPM_TOKEN
  on:
    tags: true
