language: node_js
node_js:
  - "node"
cache:
  - node_modules
branches:
  only:
    - develop
    - master
deploy:
  provider: npm
  email: contact@oddbit.id
  api_key: $NPM_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$