language: node_js
node_js:
  - "8"
cache:
  - angular/node_modules
  - dist/node_modules
  - functions/node_modules
branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+/
before_script:
  - cd angular
  - npm install
  - cd ../functions
  - npm install
  - npm run build:dist
  - cd ../dist
  - npm install
script:
  - echo "npm test is temporarily disabled"
deploy:
  provider: npm
  email: dennis@oddbit.id
  api_key: $NPM_TOKEN
  on:
    tags: true
